In [1]:
import tensorflow as tf

### Constants

In [2]:
x = tf.constant(1.0)
y = tf.constant(2.0)

Tensorflow does not print out variables and constans as expected. Session should be used to evaluate variables and constants.

In [3]:
print(x, y)

(<tf.Tensor 'Const:0' shape=() dtype=float32>, <tf.Tensor 'Const_1:0' shape=() dtype=float32>)


In [11]:
# Option 1
sess = tf.InteractiveSession()
print(sess.run([x, y]))

[1.0, 2.0]


In [12]:
# Option 2
print(x.eval(session=sess))
print(y.eval(session=sess))

1.0
2.0


In [23]:
# Operations
print("Add x and y: %s" % sess.run(tf.add(x, y)))
print("minus x from y: %s" % sess.run(tf.subtract(y, x)))
print("Multiply x and y: %s" % sess.run(tf.multiply(x, y)))
print("Divide x by y: %s" % sess.run(tf.divide(x, y)))
print("Floor Divide x by y: %s" % sess.run(tf.floor_div(x, y)))

Add x and y: 3.0
minus x from y: 1.0
Multiply x and y: 2.0
Divide x by y: 0.5
Floor Divide x by y: 0.0


### Matrices

We use a lot of linear algebra in deep learning. The following cell shows ways to create matrices. These matrices are Tensorflow variables which can be changed. This can be used as weights during training phase in machine learning problems.

In [47]:
# Randomly initialize 3 x 4 matrix drawn from normal distribution
W1 = tf.Variable(tf.random_normal([3, 4]))

# Randomly initialize 2 x 3 matrix drawn from normal distribution
W2 = tf.Variable(tf.random_uniform([2, 3]))

# Initialize 3 x 3 matrix full of ones
W3 = tf.Variable(tf.ones([3, 3]))

# Initialize 3 x 3 matrix full of zeros
W4 = tf.Variable(tf.zeros([3, 3]))

# Creates a matrix of ones with the same shape as the matrix you pass in ones_like
W5 = tf.Variable(tf.ones_like(W1))

We must initialize variables before evaluating/using them.

In [52]:
sess.run(tf.global_variables_initializer())

matrices = [W1, W2, W3, W4, W5]

for mat in matrices:
    print(mat.eval(session=sess))
    print("")

[[ 1.07220864 -1.02482951 -0.4249036  -1.48827875]
 [ 0.56416553  0.57863921 -0.05577075  1.81071723]
 [ 0.23965578 -1.9904902  -0.32923701 -0.82141447]]

[[ 0.68553174  0.49119639  0.39936161]
 [ 0.23536444  0.04026151  0.98675299]]

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]



In [69]:
# Matrix Operations
M1 = tf.Variable(tf.random_normal([3, 3]))
M2 = tf.Variable(tf.random_normal([3, 3]))

print(M1.shape, M2.shape)

sess.run(tf.global_variables_initializer())

new_matrices = [M1, M2, M1+M2, M1-M2, tf.matmul(M1, M2)]

for mat in new_matrices:
    print(sess.run(mat))
    print("")

(TensorShape([Dimension(3), Dimension(3)]), TensorShape([Dimension(3), Dimension(3)]))
[[-0.8968423   0.58434373 -2.33999085]
 [-0.47561941  1.46888912  1.86409414]
 [-0.27543172  0.86862177  0.01547491]]

[[ 1.05537069  0.59237576  0.28451738]
 [-0.73720354 -1.28444219 -0.96619344]
 [ 0.71644503 -1.19592607 -1.29383826]]

[[ 0.15852839  1.17671943 -2.05547357]
 [-1.21282291  0.18444693  0.8979007 ]
 [ 0.44101331 -0.3273043  -1.27836335]]

[[-1.95221305 -0.00803202 -2.62450814]
 [ 0.26158413  2.75333118  2.83028746]
 [-0.99187672  2.06454778  1.30931318]]

[[-3.05375624  1.51663256  2.2078135 ]
 [-0.24930406 -4.39776707 -3.96638942]
 [-0.91994667 -1.2973603  -0.93764377]]



### Placeholder

Placeholder is used to tell Tensorflow that "Values will be input later", we can define a series of computations without knowing the actual value of Placeholder.

In [71]:
c = tf.placeholder(tf.float32)
d = tf.placeholder(tf.float32)

In [73]:
sess.run(c * d, feed_dict={c: 1.0, d: 2.0})

2.0